In [11]:
import numpy as np
array1= np.array([[1,3,5],[7,9,11]])
np.save("E:\\FULL STACK PYTHON\\LibraryPrograms\\file1.npy",array1)
print("Ndarray object Data saved into the Binary File(.npy)")

Ndarray object Data saved into the Binary File(.npy)


In [12]:
import numpy as np
loaded_array = np.load("E:\\FULL STACK PYTHON\\LibraryPrograms\\file1.npy")
print(loaded_array)

[[ 1  3  5]
 [ 7  9 11]]


In [13]:
import numpy as np
array2 = np.array([[1, 3, 5],[7, 9, 11]])
np.savetxt("E:\\FULL STACK PYTHON\\LibraryPrograms\\file2.txt",array2)
print("Ndarray object Data saved into the Text File(.txt)")

Ndarray object Data saved into the Text File(.txt)


In [14]:
import numpy as np
loaded_array = np.loadtxt("E:\\FULL STACK PYTHON\\LibraryPrograms\\file2.txt")
print(loaded_array)

[[ 1.  3.  5.]
 [ 7.  9. 11.]]


In [15]:
#Save Multiple NumPy Array File(.npz Files)
import numpy as np
array1 = np.array([2, 6, 10])
array2 = np.array([4, 8, 12])
# save the two arrays into a single file
np.savez("E:\\FULL STACK PYTHON\\LibraryPrograms\\file3.npz",k=array1,v=array2)

print("Multiple Ndarray objects Data saved into the Single File (.npz)")

Multiple Ndarray objects Data saved into the Single File (.npz)


In [17]:
#Load Multiple NumPy Array File--Reading the Data from npz files
import numpy as np
load_data = np.load('E:\\FULL STACK PYTHON\\LibraryPrograms\\file3.npz')
array1 = load_data["k"]
array2 = load_data["v"]

# display the loaded arrays
print("--------------------------------------")
print(array1)
print("--------------------------------------")
print(array2)
print("--------------------------------------")


--------------------------------------
[ 2  6 10]
--------------------------------------
[ 4  8 12]
--------------------------------------
